name: Running Inventory Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn clean test

      - name: Upload Test Evidence
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-evidence
          path: ./Reports/
